version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: pkgmate-arch
    main: ./main/main.go
    binary: pkgmate
    tags: [arch]
    goos: [linux]
    goarch: [amd64]
    env: [CGO_ENABLED=1]
    ldflags:
      - -s -w -X pkgmate/ui.Version={{.Version}}
  - id: pkgmate-debian
    main: ./main/main.go
    binary: pkgmate
    tags: [dpkg]
    goos: [linux]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    ldflags:
      - -s -w -X pkgmate/ui.Version={{.Version}}
  - id: pkgmate-brew
    main: ./main/main.go
    binary: pkgmate
    tags: [brew]
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    ldflags:
      - -s -w -X pkgmate/ui.Version={{.Version}}

archives:
  - id: arch-archive
    ids: [pkgmate-arch]
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}-arch-{{ .Os }}-{{ .Arch }}"

  - id: debian-archive
    ids: [pkgmate-debian]
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}-debian-{{ .Os }}-{{ .Arch }}"

  - id: brew-archive
    ids: [pkgmate-brew]
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}-brew-{{ .Os }}-{{ .Arch }}"

signs:
  - cmd: gpg
    args:
      - "--batch"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "{{ .Env.GPG_PASSPHRASE }}"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
    artifacts: all

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.sbom.json"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^cicd:"
      - "^chore:"
      - "^refactor:"
      - "^Merge"

aurs:
  - name: pkgmate-bin
    ids: [arch-archive]
    homepage: "https://github.com/fuad-daoud/pkgmate"
    description: "TUI application to manage your dependencies"
    maintainers:
      - "Fuad Daoud <aur@fuad-daoud.com>"
    license: "MIT"
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/pkgmate-bin.git"
    commit_author:
      name: "{{ .Env.AUR_USERNAME }}"
      email: "{{ .Env.AUR_EMAIL }}"
    package: |-
      install -Dm755 "./pkgmate" "${pkgdir}/usr/bin/pkgmate"

nfpms:
  - id: pkgmate-deb
    package_name: pkgmate
    ids: [pkgmate-debian]
    vendor: Fuad Daoud
    homepage: https://github.com/fuad-daoud/pkgmate
    maintainer: Fuad Daoud <aur@fuad-daoud.com>
    description: TUI application to manage your dependencies
    license: MIT
    formats:
      - deb
    bindir: /usr/bin

homebrew_casks:
  - ids: [brew-archive]
    name: pkgmate
    homepage: "https://github.com/fuad-daoud/pkgmate"
    description: "TUI application to manage your dependencies"
    license: "MIT"
    repository:
      owner: fuad-daoud
      name: homebrew-pkgmate
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: "{{ .Env.AUR_USERNAME }}"
      email: "{{ .Env.AUR_EMAIL }}"
